Fixes #302 Fix tests in AndroidLibrary PR#214 and resubmit PR
odk-x/androidlibrary pull request #229
Opened 2022-04-03 20:38 UTC by WaltonG

Fixes #302
-Handled null pointer exception and deprecated library for the tests to pass

2022-04-04 18:50 UTC, wbrunette commented
@WaltonG. Before code is released we test it on the "development" branch. After changing the code to merge to development there is a merge problem. Can you fix? Thanks.

2022-04-04 23:05 UTC, WaltonG commented
@wbrunette The fix has been made

2022-04-04 23:21 UTC, wbrunette commented
@WaltonG note the PR still shows a conflict. The system won't let things move forward until it is resolved.
![PRScreenshot](https://user-images.githubusercontent.com/11892715/161648012-a272599b-3cb7-4196-9690-0d5c4c29c0e8.PNG)

2022-04-04 23:48 UTC, WaltonG commented
@wbrunette My thought is issue #302 is to fix tests in AndroidLibary and maintain the code. "We will need the code that was in PR#214 but we need the Android unit tests to pass."

The unit tests have passed. The merge conflict is caused by the existing code in PR#214 . Changes made to the PropertiesNonPrivilegedTest.java to have the unit test pass do not have any merge conflict

2022-04-05 11:36 UTC, wbrunette commented
@WaltonG This is part of open-source as multiple people are making changes to improve things. If something becomes out of date it needs to be brought up to date with the current state of things. That is why GitHub will not let me accept your contribution until it works with all the code. Code is constantly changing which means that to complete a task sometimes you have to bring in other changes that have happened. This is standard procedure for software engineers.

2022-04-05 11:59 UTC, WaltonG commented
@wbrunette Well understood. I'll work on the merge conflict right away

2022-04-07 00:13 UTC, WaltonG commented
@wbrunette Retry the merging to confirm resolution of the conflict

2022-04-07 01:25 UTC, wbrunette commented
@WaltonG the PR tells you if you can merge. Notice the screenshot. It is simply this same webpage.

2022-04-07 01:43 UTC, wbrunette commented
@WaltonG I know this is new to you so don't worry about taking a while. You are here to learn. However, I want you to do it the right way so you learn.

2022-04-07 19:55 UTC, wbrunette requested changes

2022-04-07 19:55 UTC, wbrunette commented on androidlibrary_lib/src/main/java/org/opendatakit/properties/PropertiesSingleton.java
> +        if(entry.getKey() != null && entry.getValue() != null)
You should have brackets around 491, 492 and 493. As you don't want to set the updatedDeviceProps flag to true unless you actually set a property.

2022-04-07 19:56 UTC, wbrunette commented
@WaltonG I fixed the merge conflicts check it out.

2022-04-07 23:35 UTC, WaltonG reviewed
@wbrunette The changes fixes it right

2022-04-08 16:57 UTC, wbrunette commented
@WaltonG while you changes do fix it, you have a logic error that I was trying to explain. If the "if" statement you put in fails, so no changes happen you still set the updated properties flag. However, you did not update the properties. Hence I requested changes and pointed out the line numbers.

2022-04-08 17:34 UTC, WaltonG commented
@wbrunette I have pushed the committed changes

2022-04-10 20:10 UTC, wbrunette approved these changes

2022-04-10 20:10 UTC, merged