Pref UI Fix
odk-x/androidlibrary pull request #252
Opened 2023-06-29 09:42 UTC by Redeem-Grimm-Satoshi

1. Theme applied to pref ui dialogs

2023-06-29 20:38 UTC, wbrunette requested changes

2023-06-30 17:21 UTC, Redeem-Grimm-Satoshi commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
It was moved to the provider package, I guess the previous developer created a separate package.

Still, I'll need further clarification if it's not what you mean or If I don't understand at all

2023-06-30 17:21 UTC, Redeem-Grimm-Satoshi commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
@wbrunette

2023-06-30 20:01 UTC, wbrunette commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
This shows your code change is moving it to the provider package. Which is why it requires the input. Maybe you accidentally dragged it in Android Studio?

2023-07-02 15:33 UTC, Redeem-Grimm-Satoshi commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
@wbrunette No I didn't move it to the provider package intentionally

2023-07-02 15:37 UTC, wbrunette commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
please move it back :) as you can see the location in the branch you are merging too has it not in provider. https://github.com/odk-x/androidlibrary/blob/outreachy-2023/androidlibrary_lib/src/androidTest/java/org/opendatakit/fragment/AlertNProgessMsgFragmentMgerTest.java

2023-07-02 15:38 UTC, wbrunette commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
this is why code reviews are done is catch things like this.

2023-07-02 22:13 UTC, Redeem-Grimm-Satoshi commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
@wbrunette I just refactored the code, the changes are located in the new commit

2023-07-02 22:14 UTC, Redeem-Grimm-Satoshi commented on androidlibrary_lib/src/androidTest/java/org/opendatakit/provider/fragment/AlertNProgessMsgFragmentMgerTest.java
> +
Moved Fragment package back to it's original location

2023-07-05 06:21 UTC, merged