Update OdkDbChunkTest
odk-x/androidlibrary pull request #262
Opened 2023-10-26 09:30 UTC by Kemyikpe

# This is a PR for [issue](https://github.com/odk-x/tool-suite-X/issues/447)

# PR Description

- Rewrite some of the test 
- Update some test and functions
- Run tests to be certain everything still works
<img width="607" alt="Screenshot 2023-10-26 at 10 14 03 AM" src="https://github.com/odk-x/androidlibrary/assets/107570182/33d74085-4dda-4951-90e8-d863d46f6480">

2023-10-26 14:40 UTC, wbrunette requested changes
You are mixing two types of asserts. The java keyword "assert" requires you to specify a flag when running. Since we are using the Junit testing environment better to be consistent and stick with Junit asserts. See two links below and search for more to learn more :)
https://medium.com/the-java-report/assertions-in-the-java-programming-language-fd64f53e7be1
https://stackoverflow.com/questions/2966347/assert-vs-junit-assertions

2023-10-27 19:13 UTC, Kemyikpe commented
> You are mixing two types of asserts. The java keyword "assert" requires you to specify a flag when running. Since we are using the Junit testing environment better to be consistent and stick with Junit asserts. See two links below and search for more to learn more :) https://medium.com/the-java-report/assertions-in-the-java-programming-language-fd64f53e7be1 https://stackoverflow.com/questions/2966347/assert-vs-junit-assertions

Fixing it now

2023-10-27 20:15 UTC, Kemyikpe commented
@wbrunette fixed the requested changes, kindly review. thank you.

2023-11-19 16:54 UTC, wbrunette approved these changes

2023-11-19 16:54 UTC, merged